// app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientSideLayout from "../components/Layout/clientLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientSideLayout>{children}</ClientSideLayout>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import { GoogleOAuthProvider } from "@react-oauth/google";
// import { Toaster } from "react-hot-toast";
// import { QueryClientProvider, QueryClient } from "@tanstack/react-query";
// import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// const queryClient = new QueryClient();

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       {/* <QueryClientProvider client={queryClient}> */}
//       <GoogleOAuthProvider clientId="274949071740-6fqckpv5aqolg0vh4h89pvvfgjvsq35c.apps.googleusercontent.com">
//         <body className={inter.className}>{children}</body>
//         <Toaster />
//         {/* <ReactQueryDevtools /> */}
//       </GoogleOAuthProvider>
//       {/* </QueryClientProvider> */}
//     </html>
//   );
// }
