import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GoogleOAuthProvider clientId="274949071740-6fqckpv5aqolg0vh4h89pvvfgjvsq35c.apps.googleusercontent.com">
        <body className={inter.className}>{children}</body>
        <Toaster />
      </GoogleOAuthProvider>
    </html>
  );
}
